# .travis.yml
language: python
python: 2.7
env:
  matrix:
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py27-dj110
install:
  - "pip install -r requirements.txt"
script:
  - tox -v
  - coverage run --source='.' example/manage.py test
  - flake8 epfl-utils
after_success:
  - coveralls
notifications:
  - recipients:
    - gregory.charmier@gmail.com
  - on_success: change
  - on_failure: change
